-- 1) 枚举类型
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_status_enum') THEN
    CREATE TYPE user_status_enum AS ENUM ('online','offline','busy');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'friend_request_status_enum') THEN
    CREATE TYPE friend_request_status_enum AS ENUM ('pending','accepted','rejected','cancelled');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'room_status_enum') THEN
    CREATE TYPE room_status_enum AS ENUM ('active','ended','cancelled');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'participant_status_enum') THEN
    CREATE TYPE participant_status_enum AS ENUM ('active','inactive','kicked','left');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'message_type_enum') THEN
    CREATE TYPE message_type_enum AS ENUM ('text','image','file','emoji','system');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'waiting_status_enum') THEN
    CREATE TYPE waiting_status_enum AS ENUM ('waiting','admitted','rejected');
  END IF;
END $$;

-- 2) updated_at 自动更新触发器
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- users
CREATE TABLE IF NOT EXISTS users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  avatar_url VARCHAR(255),
  display_name VARCHAR(100),
  personal_tag VARCHAR(100),
  status user_status_enum DEFAULT 'offline',
  last_login TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- friend_categories
CREATE TABLE IF NOT EXISTS friend_categories (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  is_system BOOLEAN DEFAULT TRUE,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- friendships
CREATE TABLE IF NOT EXISTS friendships (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL,
  friend_id INT NOT NULL,
  category_id INT NOT NULL DEFAULT 1,
  custom_category_name VARCHAR(50),
  note VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_friendships_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_friendships_friend FOREIGN KEY (friend_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_friendships_category FOREIGN KEY (category_id) REFERENCES friend_categories(id),
  CONSTRAINT unique_friendship UNIQUE (user_id, friend_id)
);

-- friend_requests
CREATE TABLE IF NOT EXISTS friend_requests (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_user_id INT NOT NULL,
  to_user_id INT NOT NULL,
  message VARCHAR(200),
  category_id INT NOT NULL DEFAULT 1,
  status friend_request_status_enum DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  responded_at TIMESTAMP NULL,
  CONSTRAINT fk_fr_from FOREIGN KEY (from_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_fr_to FOREIGN KEY (to_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_fr_cat FOREIGN KEY (category_id) REFERENCES friend_categories(id),
  CONSTRAINT unique_friend_request UNIQUE (from_user_id, to_user_id, status)
);

-- rooms
CREATE TABLE IF NOT EXISTS rooms (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_code VARCHAR(10) UNIQUE NOT NULL,
  name VARCHAR(200) NOT NULL,
  description TEXT,
  host_id INT NOT NULL,
  password VARCHAR(100),
  max_participants INT DEFAULT 50,
  is_waiting_room_enabled BOOLEAN DEFAULT TRUE,
  room_settings JSONB,
  scheduled_start TIMESTAMP NULL,
  scheduled_end TIMESTAMP NULL,
  actual_start TIMESTAMP NULL,
  actual_end TIMESTAMP NULL,
  status room_status_enum DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rooms_host FOREIGN KEY (host_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TRIGGER trg_rooms_updated_at
BEFORE UPDATE ON rooms
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- permission_roles
CREATE TABLE IF NOT EXISTS permission_roles (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name VARCHAR(50) NOT NULL UNIQUE,
  description VARCHAR(255),
  can_mute_others BOOLEAN DEFAULT FALSE,
  can_assign_cohost BOOLEAN DEFAULT FALSE,
  can_kick_participants BOOLEAN DEFAULT FALSE,
  can_record_meeting BOOLEAN DEFAULT FALSE,
  can_manage_chat BOOLEAN DEFAULT FALSE,
  can_end_meeting BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trg_permission_roles_updated_at
BEFORE UPDATE ON permission_roles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- meeting_permissions
CREATE TABLE IF NOT EXISTS meeting_permissions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id INT NOT NULL,
  user_id INT NOT NULL,
  role_id INT NOT NULL,
  assigned_by INT,
  assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NULL,
  CONSTRAINT fk_mp_meeting FOREIGN KEY (meeting_id) REFERENCES rooms(id) ON DELETE CASCADE,
  CONSTRAINT fk_mp_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_mp_role FOREIGN KEY (role_id) REFERENCES permission_roles(id),
  CONSTRAINT fk_mp_assigned_by FOREIGN KEY (assigned_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT unique_meeting_user UNIQUE (meeting_id, user_id)
);

-- room_participants
CREATE TABLE IF NOT EXISTS room_participants (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id INT NOT NULL,
  user_id INT NOT NULL,
  joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  left_at TIMESTAMP NULL,
  participant_status participant_status_enum DEFAULT 'active',
  is_muted BOOLEAN DEFAULT FALSE,
  is_video_enabled BOOLEAN DEFAULT TRUE,
  is_screen_sharing BOOLEAN DEFAULT FALSE,
  is_hand_raised BOOLEAN DEFAULT FALSE,
  can_speak BOOLEAN DEFAULT TRUE,
  can_share_screen BOOLEAN DEFAULT TRUE,
  can_enable_video BOOLEAN DEFAULT TRUE,
  can_chat BOOLEAN DEFAULT TRUE,
  last_activity TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rp_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE,
  CONSTRAINT fk_rp_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT unique_room_user UNIQUE (room_id, user_id)
);

-- messages
CREATE TABLE IF NOT EXISTS messages (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id INT NOT NULL,
  user_id INT NOT NULL,
  message_type message_type_enum DEFAULT 'text',
  content TEXT,
  file_url VARCHAR(255),
  file_name VARCHAR(255),
  file_size INT,
  parent_message_id INT NULL,
  is_edited BOOLEAN DEFAULT FALSE,
  edited_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_msg_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE,
  CONSTRAINT fk_msg_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_msg_parent FOREIGN KEY (parent_message_id) REFERENCES messages(id) ON DELETE SET NULL
);

-- waiting_room
CREATE TABLE IF NOT EXISTS waiting_room (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id INT NOT NULL,
  user_id INT NOT NULL,
  joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  admitted_by INT NULL,
  admitted_at TIMESTAMP NULL,
  status waiting_status_enum DEFAULT 'waiting',
  CONSTRAINT fk_wr_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE,
  CONSTRAINT fk_wr_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_wr_admitted_by FOREIGN KEY (admitted_by) REFERENCES users(id) ON DELETE SET NULL
);

-- meeting_recordings
CREATE TABLE IF NOT EXISTS meeting_recordings (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id INT NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rec_meeting FOREIGN KEY (meeting_id) REFERENCES rooms(id) ON DELETE CASCADE
);

-- indexes（对应你 MySQL 的索引）
CREATE INDEX IF NOT EXISTS idx_meeting_code ON rooms(meeting_code);
CREATE INDEX IF NOT EXISTS idx_host_id ON rooms(host_id);
CREATE INDEX IF NOT EXISTS idx_status ON rooms(status);
CREATE INDEX IF NOT EXISTS idx_actual_start ON rooms(actual_start);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);

CREATE INDEX IF NOT EXISTS idx_friendships_user_id ON friendships(user_id);
CREATE INDEX IF NOT EXISTS idx_friendships_friend_id ON friendships(friend_id);
CREATE INDEX IF NOT EXISTS idx_friendships_category_id ON friendships(category_id);

CREATE INDEX IF NOT EXISTS idx_friend_requests_from_user ON friend_requests(from_user_id);
CREATE INDEX IF NOT EXISTS idx_friend_requests_to_user ON friend_requests(to_user_id);
CREATE INDEX IF NOT EXISTS idx_friend_requests_status ON friend_requests(status);
CREATE INDEX IF NOT EXISTS idx_friend_requests_status_to_user ON friend_requests(status, to_user_id);

CREATE INDEX IF NOT EXISTS idx_rooms_host_id ON rooms(host_id);
CREATE INDEX IF NOT EXISTS idx_rooms_scheduled_start ON rooms(scheduled_start);

CREATE INDEX IF NOT EXISTS idx_room_participants_room_id ON room_participants(room_id);
CREATE INDEX IF NOT EXISTS idx_room_participants_user_id ON room_participants(user_id);

CREATE INDEX IF NOT EXISTS idx_messages_room_id ON messages(room_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(created_at);
CREATE INDEX IF NOT EXISTS idx_messages_user_created ON messages(user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_room_created ON messages(room_id, created_at);
CREATE INDEX IF NOT EXISTS idx_user_room ON messages(user_id, room_id);

CREATE INDEX IF NOT EXISTS idx_room_status_wr ON waiting_room(room_id, status);
CREATE INDEX IF NOT EXISTS idx_user_room_wr ON waiting_room(user_id, room_id);

CREATE INDEX IF NOT EXISTS idx_meeting_id_rec ON meeting_recordings(meeting_id);

-- init data
INSERT INTO friend_categories (name, is_system, sort_order) VALUES
('other', TRUE, 1),
('family', TRUE, 2),
('friend', TRUE, 3),
('workmate', TRUE, 4),
('boss', TRUE, 5),
('classmate', TRUE, 6),
('teacher', TRUE, 7);

INSERT INTO permission_roles (role_name, description, can_mute_others, can_assign_cohost, can_kick_participants, can_record_meeting, can_manage_chat, can_end_meeting)
VALUES
('host', '会议主持人', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
('co-host', '联席主持人', TRUE, FALSE, TRUE, TRUE, TRUE, FALSE),
('participant', '普通参会者', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE)
ON CONFLICT (role_name) DO NOTHING;
