-- 确保在 PDB XEPDB1
ALTER SESSION SET CONTAINER = XEPDB1;
CONNECT lhy/SyncPwd_111111@//localhost:1521/XEPDB1;
-- 注意：本脚本应由 gvenzl/oracle-xe 的 APP_USER（deploy/.env: ORACLE_APP_USER）执行，
-- 这样创建的表/触发器都会落在该用户 schema 下（例如 lhy）。

-- users
CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  username VARCHAR2(50) NOT NULL UNIQUE,
  email VARCHAR2(100) NOT NULL UNIQUE,
  password VARCHAR2(255) NOT NULL,
  avatar_url VARCHAR2(255),
  display_name VARCHAR2(100),
  personal_tag VARCHAR2(100),
  status VARCHAR2(10) DEFAULT 'offline' CHECK (status IN ('online','offline','busy')),
  last_login TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- friend_categories
CREATE TABLE friend_categories (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR2(50) NOT NULL,
  is_system NUMBER(1) DEFAULT 1 CHECK (is_system IN (0,1)),
  sort_order NUMBER DEFAULT 0,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- friendships
CREATE TABLE friendships (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  friend_id NUMBER NOT NULL,
  category_id NUMBER DEFAULT 1 NOT NULL,
  custom_category_name VARCHAR2(50),
  note VARCHAR2(100),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_friendships_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_friendships_friend FOREIGN KEY (friend_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_friendships_category FOREIGN KEY (category_id) REFERENCES friend_categories(id),
  CONSTRAINT unique_friendship UNIQUE (user_id, friend_id)
);

-- friend_requests
CREATE TABLE friend_requests (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  from_user_id NUMBER NOT NULL,
  to_user_id NUMBER NOT NULL,
  message VARCHAR2(200),
  category_id NUMBER DEFAULT 1 NOT NULL,
  status VARCHAR2(10) DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected','cancelled')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  responded_at TIMESTAMP NULL,
  CONSTRAINT fk_fr_from FOREIGN KEY (from_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_fr_to FOREIGN KEY (to_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_fr_cat FOREIGN KEY (category_id) REFERENCES friend_categories(id),
  CONSTRAINT unique_friend_request UNIQUE (from_user_id, to_user_id, status)
);

-- rooms
CREATE TABLE rooms (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  meeting_code VARCHAR2(10) NOT NULL UNIQUE,
  name VARCHAR2(200) NOT NULL,
  description CLOB,
  host_id NUMBER NOT NULL,
  password VARCHAR2(100),
  max_participants NUMBER DEFAULT 50,
  is_waiting_room_enabled NUMBER(1) DEFAULT 1 CHECK (is_waiting_room_enabled IN (0,1)),
  room_settings CLOB CHECK (room_settings IS JSON),
  scheduled_start TIMESTAMP NULL,
  scheduled_end TIMESTAMP NULL,
  actual_start TIMESTAMP NULL,
  actual_end TIMESTAMP NULL,
  status VARCHAR2(10) DEFAULT 'active' CHECK (status IN ('active','ended','cancelled')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_rooms_host FOREIGN KEY (host_id) REFERENCES users(id) ON DELETE CASCADE
);

-- permission_roles
CREATE TABLE permission_roles (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  role_name VARCHAR2(50) NOT NULL UNIQUE,
  description VARCHAR2(255),
  can_mute_others NUMBER(1) DEFAULT 0 CHECK (can_mute_others IN (0,1)),
  can_assign_cohost NUMBER(1) DEFAULT 0 CHECK (can_assign_cohost IN (0,1)),
  can_kick_participants NUMBER(1) DEFAULT 0 CHECK (can_kick_participants IN (0,1)),
  can_record_meeting NUMBER(1) DEFAULT 0 CHECK (can_record_meeting IN (0,1)),
  can_manage_chat NUMBER(1) DEFAULT 0 CHECK (can_manage_chat IN (0,1)),
  can_end_meeting NUMBER(1) DEFAULT 0 CHECK (can_end_meeting IN (0,1)),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- meeting_permissions
CREATE TABLE meeting_permissions (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  meeting_id NUMBER NOT NULL,
  user_id NUMBER NOT NULL,
  role_id NUMBER NOT NULL,
  assigned_by NUMBER,
  assigned_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  expires_at TIMESTAMP NULL,
  CONSTRAINT fk_mp_meeting FOREIGN KEY (meeting_id) REFERENCES rooms(id) ON DELETE CASCADE,
  CONSTRAINT fk_mp_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_mp_role FOREIGN KEY (role_id) REFERENCES permission_roles(id),
  CONSTRAINT fk_mp_assigned_by FOREIGN KEY (assigned_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT unique_meeting_user UNIQUE (meeting_id, user_id)
);

-- room_participants
CREATE TABLE room_participants (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  room_id NUMBER NOT NULL,
  user_id NUMBER NOT NULL,
  joined_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  left_at TIMESTAMP NULL,
  participant_status VARCHAR2(10) DEFAULT 'active' CHECK (participant_status IN ('active','inactive','kicked','left')),
  is_muted NUMBER(1) DEFAULT 0 CHECK (is_muted IN (0,1)),
  is_video_enabled NUMBER(1) DEFAULT 1 CHECK (is_video_enabled IN (0,1)),
  is_screen_sharing NUMBER(1) DEFAULT 0 CHECK (is_screen_sharing IN (0,1)),
  is_hand_raised NUMBER(1) DEFAULT 0 CHECK (is_hand_raised IN (0,1)),
  can_speak NUMBER(1) DEFAULT 1 CHECK (can_speak IN (0,1)),
  can_share_screen NUMBER(1) DEFAULT 1 CHECK (can_share_screen IN (0,1)),
  can_enable_video NUMBER(1) DEFAULT 1 CHECK (can_enable_video IN (0,1)),
  can_chat NUMBER(1) DEFAULT 1 CHECK (can_chat IN (0,1)),
  last_activity TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_rp_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE,
  CONSTRAINT fk_rp_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT unique_room_user UNIQUE (room_id, user_id)
);

-- messages
CREATE TABLE messages (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  room_id NUMBER NOT NULL,
  user_id NUMBER NOT NULL,
  message_type VARCHAR2(10) DEFAULT 'text' CHECK (message_type IN ('text','image','file','emoji','system')),
  content CLOB,
  file_url VARCHAR2(255),
  file_name VARCHAR2(255),
  file_size NUMBER,
  parent_message_id NUMBER NULL,
  is_edited NUMBER(1) DEFAULT 0 CHECK (is_edited IN (0,1)),
  edited_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_msg_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE,
  CONSTRAINT fk_msg_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_msg_parent FOREIGN KEY (parent_message_id) REFERENCES messages(id) ON DELETE SET NULL
);

-- waiting_room
CREATE TABLE waiting_room (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  room_id NUMBER NOT NULL,
  user_id NUMBER NOT NULL,
  joined_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  admitted_by NUMBER NULL,
  admitted_at TIMESTAMP NULL,
  status VARCHAR2(10) DEFAULT 'waiting' CHECK (status IN ('waiting','admitted','rejected')),
  CONSTRAINT fk_wr_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE,
  CONSTRAINT fk_wr_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_wr_admitted_by FOREIGN KEY (admitted_by) REFERENCES users(id) ON DELETE SET NULL
);

-- meeting_recordings
CREATE TABLE meeting_recordings (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  meeting_id NUMBER NOT NULL,
  file_path VARCHAR2(500) NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_rec_meeting FOREIGN KEY (meeting_id) REFERENCES rooms(id) ON DELETE CASCADE
);

-- 索引（对应 MySQL）
CREATE INDEX idx_meeting_code ON rooms(meeting_code);
CREATE INDEX idx_host_id ON rooms(host_id);
CREATE INDEX idx_status ON rooms(status);
CREATE INDEX idx_actual_start ON rooms(actual_start);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_username ON users(username);

CREATE INDEX idx_friendships_user_id ON friendships(user_id);
CREATE INDEX idx_friendships_friend_id ON friendships(friend_id);
CREATE INDEX idx_friendships_category_id ON friendships(category_id);

CREATE INDEX idx_friend_requests_from_user ON friend_requests(from_user_id);
CREATE INDEX idx_friend_requests_to_user ON friend_requests(to_user_id);
CREATE INDEX idx_friend_requests_status ON friend_requests(status);
CREATE INDEX idx_friend_requests_status_to_user ON friend_requests(status, to_user_id);

CREATE INDEX idx_rooms_host_id ON rooms(host_id);
CREATE INDEX idx_rooms_scheduled_start ON rooms(scheduled_start);

CREATE INDEX idx_room_participants_room_id ON room_participants(room_id);
CREATE INDEX idx_room_participants_user_id ON room_participants(user_id);

CREATE INDEX idx_messages_room_id ON messages(room_id);
CREATE INDEX idx_messages_created_at ON messages(created_at);
CREATE INDEX idx_messages_user_created ON messages(user_id, created_at);

CREATE INDEX idx_room_created ON messages(room_id, created_at);
CREATE INDEX idx_user_room ON messages(user_id, room_id);

CREATE INDEX idx_room_status_wr ON waiting_room(room_id, status);
CREATE INDEX idx_user_room_wr ON waiting_room(user_id, room_id);

CREATE INDEX idx_meeting_id_rec ON meeting_recordings(meeting_id);

-- updated_at 触发器（users/rooms/permission_roles）
CREATE OR REPLACE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_rooms_updated_at
BEFORE UPDATE ON rooms
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_permission_roles_updated_at
BEFORE UPDATE ON permission_roles
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- init data
INSERT INTO friend_categories (name, is_system, sort_order) VALUES ('other', 1, 1);
INSERT INTO friend_categories (name, is_system, sort_order) VALUES ('family', 1, 2);
INSERT INTO friend_categories (name, is_system, sort_order) VALUES ('friend', 1, 3);
INSERT INTO friend_categories (name, is_system, sort_order) VALUES ('workmate', 1, 4);
INSERT INTO friend_categories (name, is_system, sort_order) VALUES ('boss', 1, 5);
INSERT INTO friend_categories (name, is_system, sort_order) VALUES ('classmate', 1, 6);
INSERT INTO friend_categories (name, is_system, sort_order) VALUES ('teacher', 1, 7);

-- 角色（role_name 唯一，重复插入会报错：用 MERGE 规避）
MERGE INTO permission_roles t
USING (SELECT 'host' role_name FROM dual) s
ON (t.role_name = s.role_name)
WHEN NOT MATCHED THEN
  INSERT (role_name, description, can_mute_others, can_assign_cohost, can_kick_participants, can_record_meeting, can_manage_chat, can_end_meeting)
  VALUES ('host', '会议主持人', 1, 1, 1, 1, 1, 1);

MERGE INTO permission_roles t
USING (SELECT 'co-host' role_name FROM dual) s
ON (t.role_name = s.role_name)
WHEN NOT MATCHED THEN
  INSERT (role_name, description, can_mute_others, can_assign_cohost, can_kick_participants, can_record_meeting, can_manage_chat, can_end_meeting)
  VALUES ('co-host', '联席主持人', 1, 0, 1, 1, 1, 0);

MERGE INTO permission_roles t
USING (SELECT 'participant' role_name FROM dual) s
ON (t.role_name = s.role_name)
WHEN NOT MATCHED THEN
  INSERT (role_name, description, can_mute_others, can_assign_cohost, can_kick_participants, can_record_meeting, can_manage_chat, can_end_meeting)
  VALUES ('participant', '普通参会者', 0, 0, 0, 0, 0, 0);
/
