-- Sync system tables (shared concept across MySQL/Postgres/Oracle)

ALTER SESSION SET CONTAINER = XEPDB1;
CONNECT lhy/SyncPwd_111111@//localhost:1521/XEPDB1;
-- 由 APP_USER 执行（deploy/.env: ORACLE_APP_USER），无需切换 CURRENT_SCHEMA

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE change_log (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    source_db VARCHAR2(20) NOT NULL,
    table_name VARCHAR2(64) NOT NULL,
    pk_value VARCHAR2(128) NOT NULL,
    op CHAR(1) NOT NULL CHECK (op IN (''I'',''U'',''D'')),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    processed NUMBER(1) DEFAULT 0 CHECK (processed IN (0,1))
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_change_log_processed ON change_log (processed, id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_change_log_table_pk ON change_log (table_name, pk_value, id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE sync_applied (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    change_id NUMBER NOT NULL,
    target_db VARCHAR2(20) NOT NULL,
    applied_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    status VARCHAR2(10) NOT NULL CHECK (status IN (''ok'',''fail'')),
    error_text CLOB,
    CONSTRAINT uq_change_target UNIQUE (change_id, target_db),
    CONSTRAINT fk_sync_applied_change FOREIGN KEY (change_id) REFERENCES change_log(id) ON DELETE CASCADE
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE conflicts (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(64) NOT NULL,
    pk_value VARCHAR2(128) NOT NULL,
    detected_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    status VARCHAR2(20) DEFAULT ''open'' CHECK (status IN (''open'',''resolved'')),
    reason VARCHAR2(1000),
    source_db VARCHAR2(20),
    resolution_db VARCHAR2(20),
    resolution_method VARCHAR2(20),
    resolution_note VARCHAR2(255),
    resolved_by VARCHAR2(50),
    resolved_at TIMESTAMP NULL
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_conflicts_status ON conflicts (status, detected_at)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE sync_stats_daily (
    stat_date DATE PRIMARY KEY,
    total_events NUMBER DEFAULT 0,
    applied_ok NUMBER DEFAULT 0,
    applied_fail NUMBER DEFAULT 0,
    conflicts NUMBER DEFAULT 0,
    avg_lag_ms NUMBER DEFAULT 0,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE audit_log (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    source_db VARCHAR2(20) NOT NULL,
    table_name VARCHAR2(64) NOT NULL,
    pk_value VARCHAR2(128) NOT NULL,
    op CHAR(1) NOT NULL CHECK (op IN (''I'',''U'',''D'')),
    changed_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    changed_by VARCHAR2(128),
    old_row CLOB,
    new_row CLOB
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_audit_log_table_pk ON audit_log (table_name, pk_value, id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/
